// CREATEDTIME()
// LASTMODIFIED
//   | 'SETLOCALE'
//   | 'SETTIMEZONE'
//   | 'TIMESTR'
//   | 'TONOW'
//   | 'FROMNOW'
//   | 'DATESTR'
//   | 'WORKDAY'
//   | 'WORKDAYDIFF'

export type ValidDateFunctionsNamesWithSafe =
  | 'DATE'
  | 'SAFEDATE'
  | 'DATEADD'
  | 'DATESUB'
  | 'SAFEDATESUB'
  | 'SAFEDATEADD'
  | 'SAFEDATEDIFF'
  | 'DATEDIFF'
  // | 'DATEFORMAT'
  | 'DAY'
  | 'HOUR'
  | 'MINUTE'
  | 'MONTH'
  // | 'NOW'
  | 'SECOND'
  // | 'TODAY'
  | 'WEEKDAY'
  | 'WEEKNUM'
  | 'YEAR'
  | 'QUARTER'
  | 'SETYEAR'
  | 'SETQUARTER'
  | 'SETMONTH'
  | 'SETDAY'
  | 'SETWEEKNUM'
  | 'SETWEEKDAY'
  | 'SETTIME'
  | 'SETHOUR'
  | 'SETMINUTE'
  | 'SETSECOND'
  | 'STARTOF'
  | 'ENDOF'
  | 'TIMESTAMP';
// | 'DATEPARSE'

export type ValidDateFunctionsNames = Exclude<
  ValidDateFunctionsNamesWithSafe,
  'SAFEDATEADD' | 'SAFEDATESUB' | 'SAFEDATEDIFF' | 'SAFEDATE'
>;
