export type ValidNumberFunctionsNamesWithSafe =
  | 'ABS'
  | 'CEIL'
  | 'FLOOR'
  | 'EXP'
  | 'MOD'
  | 'SAFEMOD'
  | 'POWER'
  | 'ROUND'
  | 'SQRT'
  | 'SAFESQRT'
  | 'RANDOM'
  | 'SUM'
  | 'AVERAGE'
  | 'MIN'
  | 'MAX'
  | 'TONUMBER'
  | 'SAFETONUMBER'
  | 'SIN'
  | 'COS'
  | 'TAN'
  | 'COT'
  | 'ACOS'
  | 'ASIN'
  | 'ATAN'
  | 'ACOT'
  | 'PI'
  | 'LN'
  | 'LOG'
  | 'LOG10'
  | 'FIXED';

export type ValidNumberFunctionsNames = Exclude<
  ValidNumberFunctionsNamesWithSafe,
  'SAFESQRT' | 'SAFETONUMBER' | 'SAFEMOD'
>;
