export const UNIT = {
  s: 'second',
  mi: 'minute',
  h: 'hour',
  d: 'day',
  w: 'week',
  m: 'month',
  y: 'year',
};

type DateFormatsKeys =
  | 'msecond'
  | 'second'
  | 'minute'
  | 'hour12'
  | 'hour24'
  | 'year'
  | 'iweekyear'
  | 'month'
  | 'mon'
  | 'mm'
  | 'day'
  | 'dy'
  | 'ddd'
  | 'dd'
  | 'id'
  | 'week'
  | 'iweek';

type DateFormats = Record<DateFormatsKeys, string>;

// equal in psql
export const DATE_FORMATS_FORMULA: DateFormats = {
  msecond: 'MS',
  second: 'SS',
  minute: 'MI',
  hour12: 'HH',
  hour24: 'HH24',
  year: 'YYYY',
  iweekyear: 'kkkk',
  month: 'Month',
  mon: 'Mon',
  mm: 'MM',
  day: 'Day',
  dy: 'Dy',
  ddd: 'DDD',
  dd: 'DD',
  id: 'ID',
  week: 'WW',
  iweek: 'IW',
};

export const DATE_FORMATS_LUXON: DateFormats = {
  msecond: 'SSS',
  second: 'uu',
  minute: 'mm',
  hour12: 'hh',
  hour24: 'HH',
  year: 'yyyy',
  iweekyear: 'IYYY',
  month: 'LLLL',
  mon: 'LLL',
  mm: 'LL',
  day: 'cccc',
  dy: 'ccc',
  ddd: 'ooo',
  dd: 'dd',
  id: 'c',
  week: 'W',
  iweek: 'WW',
};
export const DATE_FORMAT = '"yyyy-LL-dd HH:mm:ssZZZ"';

const withSingleQuotes = (str: string) => "'" + str + "'";

// from luxon to postgres format
export const LUXON_EQUALITY_PSQL = {
  S: withSingleQuotes('S'),
  SSS: withSingleQuotes('SSS'),
  u: withSingleQuotes('u'),
  uu: withSingleQuotes('uu'),
  uuu: withSingleQuotes('uuu'),
  s: withSingleQuotes('s'),
  ss: withSingleQuotes('ss'),
  m: withSingleQuotes('m'),
  mm: withSingleQuotes('mm'),
  h: withSingleQuotes('h'),
  hh: withSingleQuotes('hh'),
  H: withSingleQuotes('H'),
  Z: withSingleQuotes('Z'),
  ZZ: withSingleQuotes('ZZ'),
  ZZZ: withSingleQuotes('ZZZ'),
  ZZZZ: withSingleQuotes('ZZZZ'),
  ZZZZZ: withSingleQuotes('ZZZZZ'),
  z: withSingleQuotes('z'),
  a: withSingleQuotes('a'),
  d: withSingleQuotes('d'),
  dd: withSingleQuotes('dd'),
  c: withSingleQuotes('c'),
  E: withSingleQuotes('E'),
  ccc: withSingleQuotes('ccc'),
  EEE: withSingleQuotes('EEE'),
  cccc: withSingleQuotes('cccc'),
  EEEE: withSingleQuotes('EEEE'),
  ccccc: withSingleQuotes('ccccc'),
  EEEEE: withSingleQuotes('EEEEE'),
  L: withSingleQuotes('L'),
  M: withSingleQuotes('M'),
  LL: withSingleQuotes('LL'),
  LLL: withSingleQuotes('LLL'),
  MMM: withSingleQuotes('MMM'),
  LLLL: withSingleQuotes('LLLL'),
  MMMM: withSingleQuotes('MMMM'),
  LLLLL: withSingleQuotes('LLLLL'),
  MMMMM: withSingleQuotes('MMMMM'),
  y: withSingleQuotes('y'),
  yy: withSingleQuotes('yy'),
  yyyy: withSingleQuotes('yyyy'),
  G: withSingleQuotes('G'),
  GG: withSingleQuotes('GG'),
  GGGGG: withSingleQuotes('GGGGG'),
  kk: withSingleQuotes('kk'),
  kkkkk: withSingleQuotes('kkkkk'),
  ii: withSingleQuotes('ii'),
  iiii: withSingleQuotes('iiii'),
  n: withSingleQuotes('n'),
  nn: withSingleQuotes('nn'),
  o: withSingleQuotes('o'),
  ooo: withSingleQuotes('ooo'),
  q: withSingleQuotes('q'),
  qq: withSingleQuotes('qq'),
  DDDD: withSingleQuotes('DDDD'),
  t: withSingleQuotes('t'),
  tt: withSingleQuotes('tt'),
  ttt: withSingleQuotes('ttt'),
  tttt: withSingleQuotes('tttt'),
  T: withSingleQuotes('T'),
  TT: withSingleQuotes('TT'),
  TTT: withSingleQuotes('TTT'),
  TTTT: withSingleQuotes('TTTT'),
  f: withSingleQuotes('f'),
  ff: withSingleQuotes('ff'),
  fff: withSingleQuotes('fff'),
  ffff: withSingleQuotes('ffff'),
  F: withSingleQuotes('F'),
  FF: withSingleQuotes('FF'),
  FFF: withSingleQuotes('FFF'),
  FFFF: withSingleQuotes('FFFF'),
  X: withSingleQuotes('X'),
  x: withSingleQuotes('x'),
  US: withSingleQuotes('US'),
  FF1: withSingleQuotes('FF1'),
  FF2: withSingleQuotes('FF2'),
  FF3: withSingleQuotes('FF3'),
  FF4: withSingleQuotes('FF4'),
  FF5: withSingleQuotes('FF5'),
  FF6: withSingleQuotes('FF6'),
  SSSS: withSingleQuotes('SSSS'),
  SSSSS: withSingleQuotes('SSSSS'),
  am: withSingleQuotes('am'),
  pm: withSingleQuotes('pm'),
  'A.M.': withSingleQuotes('A.M.'),
  'P.M.': withSingleQuotes('P.M.'),
  'a.m.': withSingleQuotes('a.m.'),
  'p.m.': withSingleQuotes('p.m.'),
  bc: withSingleQuotes('bc'),
  ad: withSingleQuotes('ad'),
  'B.C.': withSingleQuotes('B.C.'),
  'A.D.': withSingleQuotes('A.D.'),
  'b.c.': withSingleQuotes('b.c.'),
  'a.d.': withSingleQuotes('a.d.'),
  'Y,YYY': withSingleQuotes('Y,YYY'),
  // YYY: withSingleQuotes('YYY'),
  IYY: withSingleQuotes('IYY'),
  // Y: withSingleQuotes('Y'),
  I: withSingleQuotes('I'),
  MONTH: withSingleQuotes('MONTH'),
  month: withSingleQuotes('month'),
  MON: withSingleQuotes('MON'),
  mon: withSingleQuotes('mon'),
  DAY: withSingleQuotes('DAY'),
  day: withSingleQuotes('day'),
  DY: withSingleQuotes('DY'),
  dy: withSingleQuotes('dy'),
  IDDD: withSingleQuotes('IDDD'),
  ID: withSingleQuotes('ID'),
  WW: withSingleQuotes('WW'),
  IW: withSingleQuotes('IW'),
  CC: withSingleQuotes('CC'),
  J: withSingleQuotes('J'),
  RM: withSingleQuotes('RM'),
  rm: withSingleQuotes('rm'),
  W: withSingleQuotes('W'),

  // Hours
  HH: 'hh',
  HH12: 'hh',
  HH24: 'HH',

  // Minutes / Seconds
  MI: 'mm',
  SS: withSingleQuotes('SS'),
  MS: withSingleQuotes('MS'),

  // Meridiem
  AM: 'a',
  PM: 'a',

  // Years
  YYYY: 'yyyy',
  YYY: 'yyy',
  YY: 'yy',
  IYYY: 'kkkk',
  IY: 'kk',

  // Era
  BC: 'G',
  AD: 'G',

  // Months
  Month: 'LLLL',
  Mon: 'LLL',
  MM: 'LL',
  Q: 'q',

  // Days
  Day: 'cccc',
  Dy: 'ccc',
  DDD: 'ooo',
  DD: 'dd',
  D: withSingleQuotes('D'),

  // Time zones
  TZ: withSingleQuotes('TZ'),
  tz: withSingleQuotes('tz'),
  TZH: withSingleQuotes('TZH'),
  TZM: 'mm',
  OF: withSingleQuotes('OF'),
};

export const PSQL_EQUALITY_LUXON = [
  'US',
  'FF1',
  'FF2',
  'FF3',
  'FF4',
  'FF5',
  'FF6',
  'D',
  'Y,YYY',
  // 'YYY',
  'IYY',
  // 'Y',
  // 'I',
  'MONTH',
  'month',
  'MON',
  'mon',
  'DAY',
  'day',
  'DY',
  'dy',
  'IDDD',
  'ID',
  'WW',
  'IW',
  'CC',
  'W',
  'J',
  'RM',
  'rm',
  'TZ',
  'tz',
  'OF',
  'TZH',
  'S',
  'SSS',
  'u',
  'uu',
  'uuu',
  's',
  'ss',
  'm',
  'mm',
  'h',
  'hh',
  'Z',
  'ZZ',
  'ZZZ',
  'ZZZZ',
  'ZZZZZ',
  'z',
  'a',
  'd',
  'dd',
  'c',
  'E',
  'ccc',
  'EEE',
  'cccc',
  'EEEE',
  'ccccc',
  'EEEEE',
  'L',
  // 'M',
  'LL',
  'LLL',
  'MMM',
  'LLLL',
  'MMMM',
  'LLLLL',
  'MMMMM',
  'y',
  'yy',
  'yyyy',
  'G',
  'GG',
  'GGGGG',
  'kk',
  'kkkkk',
  'ii',
  'iiii',
  'n',
  'nn',
  'o',
  'ooo',
  'q',
  'qq',
  'DDDD',
  't',
  'tt',
  'ttt',
  'tttt',
  'T',
  'TT',
  'TTT',
  'TTTT',
  'f',
  'ff',
  'fff',
  'ffff',
  'F',
  'FF',
  'FFF',
  'FFFF',
  'X',
  'x',
  'SSSS',
  'SSSSS',
  'am',
  'pm',
  'A.M.',
  'P.M.',
  'a.m.',
  'p.m.',
  'bc',
  'ad',
  'B.C.',
  'A.D.',
  'b.c.',
  'a.d.',
];
