import { NUMBER, PROGRESS, STARS } from './fieldTypes';
import {
  NUMBER_NODE_TYPE,
  LITERAL_NODE_TYPE,
  BOOLEAN_NODE_TYPE,
  DATE_NODE_TYPE,
} from './nodeTypes';

export const typesMapper = {
  [PROGRESS]: NUMBER,
  [STARS]: NUMBER,
};

export const ifTypesMapper: Record<string, string> = {
  [NUMBER_NODE_TYPE + LITERAL_NODE_TYPE]: LITERAL_NODE_TYPE,
  [LITERAL_NODE_TYPE + NUMBER_NODE_TYPE]: LITERAL_NODE_TYPE,

  [BOOLEAN_NODE_TYPE + LITERAL_NODE_TYPE]: LITERAL_NODE_TYPE,
  [LITERAL_NODE_TYPE + BOOLEAN_NODE_TYPE]: LITERAL_NODE_TYPE,

  [NUMBER_NODE_TYPE + BOOLEAN_NODE_TYPE]: NUMBER_NODE_TYPE,
  [BOOLEAN_NODE_TYPE + NUMBER_NODE_TYPE]: NUMBER_NODE_TYPE,

  [LITERAL_NODE_TYPE + DATE_NODE_TYPE]: LITERAL_NODE_TYPE,
  [DATE_NODE_TYPE + LITERAL_NODE_TYPE]: LITERAL_NODE_TYPE,

  [LITERAL_NODE_TYPE + LITERAL_NODE_TYPE]: LITERAL_NODE_TYPE,
  [NUMBER_NODE_TYPE + NUMBER_NODE_TYPE]: NUMBER_NODE_TYPE,
  [DATE_NODE_TYPE + DATE_NODE_TYPE]: DATE_NODE_TYPE,
};

export const typesMapperJs: Record<string, string> = {
  [LITERAL_NODE_TYPE]: 'String',
  [NUMBER_NODE_TYPE]: 'Number',
  [DATE_NODE_TYPE]: 'Date',
  [BOOLEAN_NODE_TYPE]: 'Boolean',
};

export const typesMapperSql: Record<string, string> = {
  [LITERAL_NODE_TYPE]: 'TEXT',
  [NUMBER_NODE_TYPE]: 'NUMERIC',
  [DATE_NODE_TYPE]: 'TIMESTAMPTZ',
  [BOOLEAN_NODE_TYPE]: 'BOOLEAN',
};
